apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-credentials-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-credentials-server
  template:
    metadata:
      labels:
        app: client-credentials-server
    spec:
      containers:
        - name: client-credentials-server-container
          image: client-credentials-server
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000