POST http://localhost:3846/client
Authorization: Basic my-client foobar
Content-Type: application/x-www-form-urlencoded

client_id=my-client&client_secret=foobar&grant_type=client_credentials&scope=photos+openid+offline

###
